Adding the Flutter splash project as part of the bundle
ubuntu/WSL pull request #122
Opened 2022-03-24 13:51 UTC by CarlosNihelton

This PR aims to bring the Flutter splash screen as a submodule of the launcher and bundle its build artifacts into the generated appx bundle. This is done by:

- Adding the Flutter repository as a submodule;
- Making the CI fetch and build it;
- Make the Appx project automatically bundle the Flutter build artifacts. This is achieved by the `Directory.build.props` file added to the Appx project directory.
- Ensuring the availability of the VC++ runtime on the target host. Achieved by adding the PackageDependency declaration to the `DistroLauncher-Appx` project.

The current form of this PR has some drawbacks that require more time to address and I don't think we should block on those right now. They are:
- Flutter build artifacts are unconditionally bundled to the appx, no matter if they will be usable or not (currently only UbuntuPreview will make use of them);
- Flutter build artifacts built for x64 are bundled inside ARM64 packages. Flutter does not currently support ARM64 Windows targets, so the launcher will not even try to make use of those artifacts. 
- Splash flutter app is built at every iteration of the build matrix. Mainly because the icon can change between WSLID's.

Those issues are main inneficiences, they won't harm the experience by now, but must be adressed soon, IMHO.
I'm sure there is some combination of parameters for MSBuild to conditionally bundle the Flutter artifacts, but I didn't figure out yet.

2022-03-24 16:10 UTC, CarlosNihelton commented
Sample taken from the sideload bundle generated by [this successful run](https://github.com/ubuntu/WSL/actions/runs/2035204914), with the Flutter artifacts highlighted in both x64 and ARM64 appx.

![image](https://user-images.githubusercontent.com/11138291/159960319-a6042524-d4f8-450c-83b5-445b8712db28.png)

![image](https://user-images.githubusercontent.com/11138291/159960556-8d05bc89-7055-4907-910a-03ed557f8d7e.png)

2022-03-30 17:50 UTC, CarlosNihelton commented
With the latest merge, this requires a careful reassessment whether it's ready or not. Let me put as draft for now.

2022-04-04 19:27 UTC, CarlosNihelton commented
#138 wants to undo the changes that target specific releases. I didn't want to apply those across all releases, since the prior ones will not benefit from the OOBE or the slide show.

2022-04-04 19:56 UTC, CarlosNihelton commented
Flutter steps are skipped when building older releases:

![image](https://user-images.githubusercontent.com/11138291/161621557-7d0f79b2-57fe-4e3f-b5ae-c119034fcd22.png)

While for the newers are not:

![image](https://user-images.githubusercontent.com/11138291/161621659-c5ce7867-8643-4999-be1e-d66b843a8924.png)

2022-04-04 20:23 UTC, CarlosNihelton commented
The UbuntuPreview sideload bundle genereted [in this run](https://github.com/ubuntu/WSL/actions/runs/2092052527) contains the artifacts generated by Flutter inside the app bundle as expected per the explanation above.

x64 APPX:

![image](https://user-images.githubusercontent.com/11138291/161625408-6c463400-cb2a-4aa1-aead-12e34b37f21b.png)

ARM64 APPX:

![image](https://user-images.githubusercontent.com/11138291/161625562-83d9ee77-324c-4e48-8857-a199bd27994b.png)

2022-04-05 08:08 UTC, didrocks requested changes
Happy that you got the flutter project separated and shipped in the bundle, nice work!

So, I’m not going to approve this right away, I think there are some drawbacks:
> To make it specific to the releases that feature the OOBE, the referred build system file is added to the meta/generated directories.
 and as you noticed:
> https://github.com/ubuntu/WSL/pull/138

The idea here is to never change manually the `generated` directories, as they are… generated! Also, ideally, we would avoid shipping things in `meta/src` for the point releases, as it means, everytime we open a new release, we will need to copy them.

So basically, the "master template" (as being project root content) corresponds to the next versioned LTS. Then, we can override previous versions.

So, the `appxmanifest` can be directly changed in the project directly. I don’t think there are some impacts on declaring it as UPW for all versions, right?

Then, the remaining question is about `Directory.build.props`. We should (by the logic above), ship it in `DistroLauncher-Appx/`. Then, we can have 2 strategies:
* either ships it everywhere (even if not used in older releases)
* or for those releases, have an empty override file in `src`, like `meta/Ubuntu20.004LTS/src/DistroLauncher-Appx/Directory.build.props`. Then, the github action workflow logic to install and build the flutter app can be changed to compare it to an empty sha256 or to `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` which seems to be the "empty file" sha256… or you can directly compare in the workflow with a `hasfiles()` of a known empty file, which is even more robust.

What do you think?

2022-04-05 10:23 UTC, CarlosNihelton commented
> Happy that you got the flutter project separated and shipped in the bundle, nice work!
> 
> So, I’m not going to approve this right away, I think there are some drawbacks:
> 
> > To make it specific to the releases that feature the OOBE, the referred build system file is added to the meta/generated directories.
> > and as you noticed:
> > #138
> 
> The idea here is to never change manually the `generated` directories, as they are… generated! Also, ideally, we would avoid shipping things in `meta/src` for the point releases, as it means, everytime we open a new release, we will need to copy them.
> 
> So basically, the "master template" (as being project root content) corresponds to the next versioned LTS. Then, we can override previous versions.
> 
> So, the `appxmanifest` can be directly changed in the project directly. I don’t think there are some impacts on declaring it as UPW for all versions, right?
> 
> Then, the remaining question is about `Directory.build.props`. We should (by the logic above), ship it in `DistroLauncher-Appx/`. Then, we can have 2 strategies:
> 
> * either ships it everywhere (even if not used in older releases)
> * or for those releases, have an empty override file in `src`, like `meta/Ubuntu20.004LTS/src/DistroLauncher-Appx/Directory.build.props`. Then, the github action workflow logic to install and build the flutter app can be changed to compare it to an empty sha256 or to `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` which seems to be the "empty file" sha256… or you can directly compare in the workflow with a `hasfiles()` of a known empty file, which is even more robust.
> 
> What do you think?

I like the second option better, honestly. The only caviat is that the file cannot be completely empty, it must have the root element (<Project/>) declaration. But since that content will be exactly the same for the releases that won't feature the slide show, the comparison strategy remains the same, only the SHA changes to `9907733AF732AB3F3A691E9C3C0D55FEE72FDAFDAC410D639D46899A3169342D`  (according to Powershell) for the file containing only:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" />

```

2022-04-05 17:34 UTC, CarlosNihelton commented
Updated runs for:

- [Ubuntu22.04LTS (Jammy)](https://github.com/ubuntu/WSL/actions/runs/2097396165)

![image](https://user-images.githubusercontent.com/11138291/161802930-07e62bfd-28c7-4654-b6f5-efbb12a94d2e.png)


- [Ubuntu20.04LTS](https://github.com/ubuntu/WSL/actions/runs/2097228050)

![image](https://user-images.githubusercontent.com/11138291/161802842-96a99e70-d58e-4f27-8cc1-86454d16e7e4.png)


As expected the Jammy app bundle contains the Flutter artifacts while the Focal doesn't.

2022-04-06 06:52 UTC, didrocks approved these changes
Let’s merge this as this is behaving as expected now. Do you mind having a look at my comment about naming and doing another PR with those fixed?

Thanks!

2022-04-06 06:52 UTC, didrocks commented on .github/workflows/build-wsl.yaml
> +            echo "Skipping Flutter steps due hashes comparing equal:"
The message could be enhanced to be due to the result: "Directory.build.props not doing anything" or so.

2022-04-06 06:52 UTC, didrocks commented on .github/workflows/build-wsl.yaml
> +          META_TREE_HASH=$(sha256sum meta/Ubuntu18.04LTS/generated/DistroLauncher-Appx/Directory.build.props | cut -f1 -d' ')
Rather than META_TREE_HASH, I would give it more sense, like "NOOP_HASH"

2022-04-06 06:52 UTC, merged