End-to-end testing bed preparation script
ubuntu/WSL pull request #294
Opened 2022-10-10 17:31 UTC by CarlosNihelton

This PR adds a script to be invoked either locally or via CI to build the end-to-end testing enabled application package bundle.

I'd love to receive a recommendation for a better way to `FailFast`. That looks ugly to me, but Powershell is not on my skillset. 😅 

To test it locally, run from the repository root:

```
.\e2e\pre-e2e-testing.ps1 -AppID "UbuntuPreview" -RootfsX64 <rootfs_URL> -CertificateThumbprint <your_pfx_thumbprint>

$env:LAUNCHER_REPO_ROOT=$(pwd).Path

cd .\e2e

go test .\test-runner --distro-name Ubuntu-Preview --launcher-name ubuntupreview.exe
```

Rootfs URL can be a local path.

### Why not making the script run the tests as well?

My reasoning was that we will more often touch the interpreted code (`test-runner` Go module and the Flutter automation code) then the compiled one (`ui-driver` Go module and the C++ distro launcher or even the rootfs) when interacting with the end-to-end test. Thus, using this script as a convenient way to invoke the test runner would be an overkill.

The script should simplify getting from the pristine repository to a working test setup by building and installing the appx. After that, the developer should be free to iterate over the testing scenarios. CI will do the same soon.

2022-10-11 14:54 UTC, EduardGomezEscandell requested changes
Small typo only

2022-10-11 14:54 UTC, EduardGomezEscandell commented on e2e/pre-e2e-testing.ps1
> +    [Parameter(Mandatory=$true, HelpMessage="UbuntuPreview, Ubuntu22.04LTS etc etc.")]
```suggestion
    [Parameter(Mandatory=$true, HelpMessage="UbuntuPreview, Ubuntu22.04LTS, etc.")]

```

2022-10-11 15:09 UTC, EduardGomezEscandell commented
For reference, I first uninstalled Ubuntu Preview, then I ran the local tests by copy-pasting  this in the Developer Powershell for VS console (it's basicallly the same as in the description):

```powershell
cd $env:LAUNCHER_REPO_ROOT # This I have already setup on my machine 😄 

$distroName = "Ubuntu-Preview"
$appId = "UbuntuPreview"
$launcher = "ubuntupreview.exe"

$rootfs = "..\images\jammy.tar.gz" # Tests only work for me with jammy 👀
$thumbprint = (Get-ChildItem -Path Cert:\LocalMachine\TrustedPeople\ | Where-Object {$_.FriendlyName -Match "Ubuntu WSL"}).thumbprint

# This is needed to get around the execution policy:
powershell.exe -ExecutionPolicy Bypass -command ".\e2e\pre-e2e-testing.ps1 -AppID $appId -RootfsX64 $rootfs -CertificateThumbprint $thumbprint"

cd .\e2e

go test .\test-runner --distro-name $distroName --launcher-name $launcher
```

The tests fail to spawn the OOBE with Kinetic (both last week's and September 26th's image, haven't tried more recent).

2022-10-13 13:42 UTC, EduardGomezEscandell commented on e2e/pre-e2e-testing.ps1
> +cp ./e2e/ui-driver/ui-driver.props DistroLauncher-Appx/
```suggestion
Copy-Item ./e2e/ui-driver/ui-driver.props DistroLauncher-Appx/
```
Very minor nitpick: the VSCode linter recommends not using aliases and instead use full names. https://learn.microsoft.com/es-es/powershell/utility-modules/psscriptanalyzer/rules/AvoidUsingCmdletAliases?view=ps-modules

I don't know much powershell, I'm just the messenger 😅

2022-10-17 15:37 UTC, CarlosNihelton commented
I think we have enough understanding and confidence that this can be merged.

2022-10-17 16:23 UTC, EduardGomezEscandell approved these changes
> I think we have enough understanding and confidence that this can be merged.

Agreed

2022-10-17 16:26 UTC, EduardGomezEscandell commented
Also for future reference:

The reason why the server never started was that, for some reason, I had an empty rootfs tarball. I re-downloaded it then ran the script again and all worked fine.

2022-10-17 16:44 UTC, merged