Default setup experience to bypass Ubuntu OOBE
ubuntu/WSL pull request #315
Opened 2022-10-25 19:54 UTC by CarlosNihelton

My original intent to implement this was to adjust only the appxmanifest files. But then I got a question: is `wsl --install` supposed to execute the appxmanifest entry point or invoke the distro launcher directly (most likely with no arguments)? I don't really know the answer, but I suspect it is the latest and that requires consistency between that behavior and installation through the store.

Thus, in the following set of changes I'm preparing both scenarios:

1. The one-line change in the `DistroLauncher-Appx/MyDistro.appxmanifest` makes the entry point for all apps to be `<launcher.exe> --ui=none`, thus following the upstream setup experience (the one existing in Ubuntu 18.04 and 20.04 - prior to the Ubuntu OOBE) [d08bdc84135e0c3b8a7b5f8f24cc5d2b48de558a]
2. The same change is applied to `meta/*/generated/DistroLauncher-Appx/MyDistro.appxmanifest` as that's the way `wsl-builder` is supposed to parameterize the builds. That's a consequence of the change mentioned above (1). [f2d90f1912f16e98a566d9b114c770067221a500]
3. `meta/UbuntuPreview/src/DistroLauncher-Appx/MyDistro.appxmanifest` was created to preserve the Ubuntu-Preview app from those changes. For that app the entry point remains `ubuntupreview.exe --hide-console` (that's the way the Start Menu and the App Installer invoke it) and the OOBE is implicitly enabled as used to be before this pull request. The file just created act as the override for the changes above preserving the current behavior for the Ubuntu Preview app.  [767d39ee3d44e6b63ee56de28ce93dd658161c59]
4. Covers the scenario in which `wsl --install` would invoke the distro launcher directly (with empty args) instead of following the appxmanifest entry point. [dc69de3741297f7217c575c005ff356c25c6ffc6] The end result of this change is that any of the following launcher invocations would result in the default upstream setup experience being following instead of our OOBE:

```
<launcher.exe>
<launcher.exe> install
<launcher.exe> <any invalid combination of parameters> -- as used to be.
```

2022-10-25 20:54 UTC, CarlosNihelton commented
See #316 for the end-to-end test failure. Ideally, we should get that one merged first and rebase this one to make sure we don't have any issues lurking around, just in case.

2022-10-25 21:40 UTC, CarlosNihelton commented
See the following runs for sideload apps built with this branch for experimentation:

- [UbuntuPreview](https://github.com/ubuntu/WSL/actions/runs/3324375562)
- [Ubuntu22.04LTS](https://github.com/ubuntu/WSL/actions/runs/3324380598)
- [Ubuntu](https://github.com/ubuntu/WSL/actions/runs/3324480504)

2022-10-26 06:39 UTC, EduardGomezEscandell requested changes
Questions regarding AppManifest for Ubuntu Preview

2022-10-26 06:39 UTC, EduardGomezEscandell commented on meta/UbuntuPreview/src/DistroLauncher-Appx/MyDistro.appxmanifest
> +    <DisplayName>UbuntuDev.FullName.Dev</DisplayName>
Should this be Ubuntu Preview?

2022-10-26 06:39 UTC, EduardGomezEscandell commented on meta/UbuntuPreview/src/DistroLauncher-Appx/MyDistro.appxmanifest
> +      <uap:VisualElements DisplayName="UbuntuDev.FullName.Dev" Description="UbuntuDev.FullName.Dev on Windows" Square150x150Logo="Assets\Square150x150Logo.png" Square44x44Logo="Assets\Square44x44Logo
Same here

2022-10-26 06:39 UTC, EduardGomezEscandell commented on meta/UbuntuPreview/src/DistroLauncher-Appx/MyDistro.appxmanifest
> +                             DisplayName="UbuntuDev.FullName.Dev"
Also here

2022-10-26 07:46 UTC, EduardGomezEscandell commented
Ubuntu and Ubuntu Preview install fine (although fixing snapd is a bit cumbersome, we should build with a rootfs shipping some version other than snap 2.57.4). 

I cannot install Ubuntu-Preview, I have the same PRI error we used to have:

Original:
> Mensaje de error en la instalación de la aplicación: Merge failure for shared merged PRI file: error 0x80070490: no se puede registrar el paquete CanonicalGroupLimited.UbuntuPreview_2210.0.9999.0_x64__79rhkp1fndgsc porque hubo un error de combinación con el siguiente archivo: C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuPreview_2210.0.9999.0_neutral_split.scale-100_79rhkp1fndgsc\resources.pri (0x80070490)

DeepL translation:
> Error message on application installation: Merge failure for shared merged PRI file: error 0x80070490: unable to register the package CanonicalGroupLimited.UbuntuPreview_2210.0.9999.0_x64__79rhkp1fndgsc because there was a merge failure with the following file: C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuPreview_2210.0.9999.0_neutral_split.scale-100_79rhkp1fndgsc\resources.pri (0x80070490)

2022-10-26 10:14 UTC, CarlosNihelton commented on meta/UbuntuPreview/src/DistroLauncher-Appx/MyDistro.appxmanifest
> +      <uap:VisualElements DisplayName="UbuntuDev.FullName.Dev" Description="UbuntuDev.FullName.Dev on Windows" Square150x150Logo="Assets\Square150x150Logo.png" Square44x44Logo="Assets\Square44x44Logo
Ditto

2022-10-26 10:14 UTC, CarlosNihelton commented on meta/UbuntuPreview/src/DistroLauncher-Appx/MyDistro.appxmanifest
> +                             DisplayName="UbuntuDev.FullName.Dev"
Ditto

2022-10-26 10:44 UTC, CarlosNihelton commented
> See the following runs for sideload apps built with this branch for experimentation:
> 
> * [UbuntuPreview](https://github.com/ubuntu/WSL/actions/runs/3324375562)
> * [Ubuntu22.04LTS](https://github.com/ubuntu/WSL/actions/runs/3324380598)
> * [Ubuntu](https://github.com/ubuntu/WSL/actions/runs/3324480504)

Updated [UbuntuPreview build](https://github.com/ubuntu/WSL/actions/runs/3328300005)

2022-10-26 15:58 UTC, EduardGomezEscandell approved these changes
New sideload works!

2022-10-26 15:58 UTC, EduardGomezEscandell commented
To be noted: there is a UTF16 / UTF8 encooding error in the slideshow:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/47142856/198076068-109cccb1-fff5-4194-b698-c8773c2273bf.png">

2022-10-26 16:17 UTC, merged