Modernize default upgrade policy patch
ubuntu/WSL pull request #383
Opened 2023-05-08 09:42 UTC by EduardGomezEscandell

The upgrade policy change needs to reboot the machine, which messes with systemd’s first boot.

Back when this was implemented, we wanted this patch to afect pre-existing distros. Any pre-existing distro will have received the patch by now, so we no longer need this requirement.

This’ll also speed up install time.

UDENG-268

2023-05-08 09:57 UTC, EduardGomezEscandell commented on DistroLauncher/Patch.cpp
> +        auto it = getline(unused, line);
`it` seems like a perfectly fine name for an iterator.

2023-05-10 15:06 UTC, CarlosNihelton commented on DistroLauncher/Patch.cpp
> +        auto it = getline(unused, line);
I agree. Let's add it to the `.clang-tidy`'s allow list for variable and parameter names:

```
CheckOptions:
  - key: readability-identifier-length.IgnoredParameterNames
    value: "hr|ok|st"
  - key: readability-identifier-length.IgnoredVariableNames
    value: "hr|ok|st"
```

2023-05-10 15:23 UTC, CarlosNihelton commented on DistroLauncher/Patch.cpp
> +    bool SetDefaultUpgradePolicy(std::istreambuf_iterator<char> unused, std::ostream& output)
A minor thing: `unused` is being used, so we should assign a more meaningful name.

2023-05-10 17:12 UTC, CarlosNihelton requested changes
Two observations only:

- the `it` naming 
- the `unused` parameter being used.

2023-05-12 11:57 UTC, CarlosNihelton approved these changes
LGTM!

2023-05-12 12:34 UTC, EduardGomezEscandell commented
Force-pushed to rebase main. Will merge if/when tests pass.

2023-05-17 13:07 UTC, merged